# Generated by Django 3.2.9 on 2022-01-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1232-09-23'),
            preserve_default=False,
        ),
    ]
